version: "3.9"
services:

  nginx:
    build: ./nginx/
    restart: always
    volumes:
      - uwsgi_data:/tmp/uwsgi/
      - web_static:/var/www/mysite/assets/:ro
    ports:
      - "8000:80"
    depends_on: 
      - web

  web:
    build: .
    restart: always
    volumes:
      - uwsgi_data:/tmp/uwsgi/
      - web_static:/var/www/mysite/assets/


volumes:
  uwsgi_data:
  web_static:
